[ASC] Add missing header after d978f4ece795
_studio/shared/asc/src/asc.cpp:1129:26: error: no member named 'log' in namespace 'std'
    result = ((c1 * std::log(x)) + c0) >= y;
                    ~~~~~^